---
plugin: community.general.proxmox
url: "https://{{ lookup('ansible.builtin.env', 'PLAYGROUND_PROXMOX_HOST') }}:8006"
user: "{{ lookup('ansible.builtin.env', 'PLAYGROUND_PROXMOX_API_TOKEN') | ansible.builtin.split('!') | first }}"
token_id: "{{ lookup('ansible.builtin.env', 'PLAYGROUND_PROXMOX_API_TOKEN') | ansible.builtin.regex_search('!(\\w+)=', '\\1') | first }}"
token_secret: "{{ lookup('ansible.builtin.env', 'PLAYGROUND_PROXMOX_API_TOKEN') | ansible.builtin.split('=') | last }}"
validate_certs: false
want_facts: true
exclude_nodes: true
groups:
  playground: "lookup('ansible.builtin.env', 'PLAYGROUND_PROXMOX_VM_PREFIX') in (proxmox_tags_parsed | list | sort)"
compose:
  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')
  # NOTE: (vadimk) this is hardcodded for now
  ansible_user: "'ubuntu'"
